// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: aether/auction/v1beta1/biddings.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SurplusBiddings struct {
	BiddingId           uint64                                  `protobuf:"varint,1,opt,name=bidding_id,json=biddingId,proto3" json:"bidding_id,omitempty" yaml:"bidding_id"`
	AuctionId           uint64                                  `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty" yaml:"auction_id"`
	AuctionStatus       string                                  `protobuf:"bytes,3,opt,name=auction_status,json=auctionStatus,proto3" json:"auction_status,omitempty" yaml:"auction_status"`
	AuctionedCollateral github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,4,opt,name=auctioned_collateral,json=auctionedCollateral,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"auctioned_collateral" yaml:"auctioned_collateral"`
	Bidder              string                                  `protobuf:"bytes,5,opt,name=bidder,proto3" json:"bidder,omitempty" yaml:"bidder"`
	Bid                 github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,6,opt,name=bid,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"bid" yaml:"bid"`
	BiddingTimestamp    time.Time                               `protobuf:"bytes,7,opt,name=bidding_timestamp,json=biddingTimestamp,proto3,stdtime" json:"bidding_timestamp" yaml:"bidding_timestamp"`
	BiddingStatus       string                                  `protobuf:"bytes,8,opt,name=bidding_status,json=biddingStatus,proto3" json:"bidding_status,omitempty" yaml:"bidding_status"`
	AuctionMappingId    uint64                                  `protobuf:"varint,9,opt,name=auction_mapping_id,json=auctionMappingId,proto3" json:"auction_mapping_id,omitempty" yaml:"auction_mapping_id"`
	AppId               uint64                                  `protobuf:"varint,10,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
}

func (m *SurplusBiddings) Reset()         { *m = SurplusBiddings{} }
func (m *SurplusBiddings) String() string { return proto.CompactTextString(m) }
func (*SurplusBiddings) ProtoMessage()    {}
func (*SurplusBiddings) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c2ab45cbab30f38, []int{0}
}
func (m *SurplusBiddings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SurplusBiddings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SurplusBiddings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SurplusBiddings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SurplusBiddings.Merge(m, src)
}
func (m *SurplusBiddings) XXX_Size() int {
	return m.Size()
}
func (m *SurplusBiddings) XXX_DiscardUnknown() {
	xxx_messageInfo_SurplusBiddings.DiscardUnknown(m)
}

var xxx_messageInfo_SurplusBiddings proto.InternalMessageInfo

type DebtBiddings struct {
	BiddingId        uint64                                  `protobuf:"varint,1,opt,name=bidding_id,json=biddingId,proto3" json:"bidding_id,omitempty" yaml:"bidding_id"`
	AuctionId        uint64                                  `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty" yaml:"auction_id"`
	AuctionStatus    string                                  `protobuf:"bytes,3,opt,name=auction_status,json=auctionStatus,proto3" json:"auction_status,omitempty" yaml:"auction_status"`
	OutflowTokens    github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,4,opt,name=outflow_tokens,json=outflowTokens,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"outflow_tokens" yaml:"outflow_tokens"`
	Bidder           string                                  `protobuf:"bytes,5,opt,name=bidder,proto3" json:"bidder,omitempty" yaml:"bidder"`
	Bid              github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,6,opt,name=bid,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"bid" yaml:"bid"`
	BiddingTimestamp time.Time                               `protobuf:"bytes,7,opt,name=bidding_timestamp,json=biddingTimestamp,proto3,stdtime" json:"bidding_timestamp" yaml:"bidding_timestamp"`
	BiddingStatus    string                                  `protobuf:"bytes,8,opt,name=bidding_status,json=biddingStatus,proto3" json:"bidding_status,omitempty" yaml:"bidding_status"`
	AuctionMappingId uint64                                  `protobuf:"varint,9,opt,name=auction_mapping_id,json=auctionMappingId,proto3" json:"auction_mapping_id,omitempty" yaml:"auction_mapping_id"`
	AppId            uint64                                  `protobuf:"varint,10,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
}

func (m *DebtBiddings) Reset()         { *m = DebtBiddings{} }
func (m *DebtBiddings) String() string { return proto.CompactTextString(m) }
func (*DebtBiddings) ProtoMessage()    {}
func (*DebtBiddings) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c2ab45cbab30f38, []int{1}
}
func (m *DebtBiddings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DebtBiddings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DebtBiddings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DebtBiddings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DebtBiddings.Merge(m, src)
}
func (m *DebtBiddings) XXX_Size() int {
	return m.Size()
}
func (m *DebtBiddings) XXX_DiscardUnknown() {
	xxx_messageInfo_DebtBiddings.DiscardUnknown(m)
}

var xxx_messageInfo_DebtBiddings proto.InternalMessageInfo

type DutchBiddings struct {
	BiddingId          uint64                                  `protobuf:"varint,1,opt,name=bidding_id,json=biddingId,proto3" json:"bidding_id,omitempty" yaml:"bidding_id"`
	AuctionId          uint64                                  `protobuf:"varint,2,opt,name=auction_id,json=auctionId,proto3" json:"auction_id,omitempty" yaml:"auction_id"`
	AuctionStatus      string                                  `protobuf:"bytes,3,opt,name=auction_status,json=auctionStatus,proto3" json:"auction_status,omitempty" yaml:"auction_status"`
	OutflowTokenAmount github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,4,opt,name=outflow_token_amount,json=outflowTokenAmount,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"outflow_token_amount" yaml:"outflow_token_amount"`
	InflowTokenAmount  github_com_cosmos_cosmos_sdk_types.Coin `protobuf:"bytes,5,opt,name=inflow_token_amount,json=inflowTokenAmount,proto3,casttype=github.com/cosmos/cosmos-sdk/types.Coin" json:"inflow_token_amount" yaml:"inflow_token_amount"`
	Bidder             string                                  `protobuf:"bytes,6,opt,name=bidder,proto3" json:"bidder,omitempty" yaml:"bidder"`
	BiddingTimestamp   time.Time                               `protobuf:"bytes,7,opt,name=bidding_timestamp,json=biddingTimestamp,proto3,stdtime" json:"bidding_timestamp" yaml:"bidding_timestamp"`
	BiddingStatus      string                                  `protobuf:"bytes,8,opt,name=bidding_status,json=biddingStatus,proto3" json:"bidding_status,omitempty" yaml:"bidding_status"`
	AuctionMappingId   uint64                                  `protobuf:"varint,9,opt,name=auction_mapping_id,json=auctionMappingId,proto3" json:"auction_mapping_id,omitempty" yaml:"auction_mapping_id"`
	AppId              uint64                                  `protobuf:"varint,10,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty" yaml:"app_id"`
}

func (m *DutchBiddings) Reset()         { *m = DutchBiddings{} }
func (m *DutchBiddings) String() string { return proto.CompactTextString(m) }
func (*DutchBiddings) ProtoMessage()    {}
func (*DutchBiddings) Descriptor() ([]byte, []int) {
	return fileDescriptor_6c2ab45cbab30f38, []int{2}
}
func (m *DutchBiddings) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DutchBiddings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DutchBiddings.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DutchBiddings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DutchBiddings.Merge(m, src)
}
func (m *DutchBiddings) XXX_Size() int {
	return m.Size()
}
func (m *DutchBiddings) XXX_DiscardUnknown() {
	xxx_messageInfo_DutchBiddings.DiscardUnknown(m)
}

var xxx_messageInfo_DutchBiddings proto.InternalMessageInfo

func init() {
	proto.RegisterType((*SurplusBiddings)(nil), "aether.auction.v1beta1.SurplusBiddings")
	proto.RegisterType((*DebtBiddings)(nil), "aether.auction.v1beta1.DebtBiddings")
	proto.RegisterType((*DutchBiddings)(nil), "aether.auction.v1beta1.DutchBiddings")
}

func init() {
	proto.RegisterFile("aether/auction/v1beta1/biddings.proto", fileDescriptor_6c2ab45cbab30f38)
}

var fileDescriptor_6c2ab45cbab30f38 = []byte{
	// 679 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x56, 0x4f, 0x4f, 0xd4, 0x5e,
	0x14, 0x9d, 0xfe, 0x80, 0xfe, 0x9c, 0xa7, 0x83, 0x4c, 0x01, 0x53, 0xc6, 0xd8, 0x92, 0x46, 0xe3,
	0xb8, 0xb0, 0x0d, 0xea, 0xca, 0xc4, 0x44, 0x07, 0x16, 0x4e, 0x0c, 0x26, 0x16, 0x56, 0x6e, 0x26,
	0xaf, 0xd3, 0x47, 0xa9, 0xd3, 0xf6, 0x35, 0xed, 0xab, 0xc8, 0x37, 0x30, 0xae, 0x58, 0x9a, 0xa8,
	0x7b, 0x3f, 0x0a, 0xee, 0x58, 0xba, 0xaa, 0x3a, 0x7c, 0x83, 0x59, 0xba, 0x32, 0x7d, 0xbd, 0xed,
	0x4c, 0x91, 0x64, 0x9c, 0x25, 0x09, 0x2b, 0x78, 0xf7, 0xcf, 0xb9, 0x87, 0x7b, 0xcf, 0x09, 0x45,
	0x77, 0x30, 0x61, 0xfb, 0x24, 0x32, 0x70, 0xd2, 0x67, 0x2e, 0x0d, 0x8c, 0xb7, 0x1b, 0x16, 0x61,
	0x78, 0xc3, 0xb0, 0x5c, 0xdb, 0x76, 0x03, 0x27, 0xd6, 0xc3, 0x88, 0x32, 0x2a, 0xdd, 0xc8, 0xcb,
	0x74, 0x28, 0xd3, 0xa1, 0xac, 0xb5, 0xe2, 0x50, 0x87, 0xf2, 0x12, 0x23, 0xfb, 0x2d, 0xaf, 0x6e,
	0xa9, 0x0e, 0xa5, 0x8e, 0x47, 0x0c, 0xfe, 0xb2, 0x92, 0x3d, 0x83, 0xb9, 0x3e, 0x89, 0x19, 0xf6,
	0x43, 0x28, 0x50, 0xfa, 0x34, 0xf6, 0x69, 0x6c, 0x58, 0x38, 0x26, 0xe5, 0xc8, 0x3e, 0x75, 0x83,
	0x3c, 0xaf, 0x7d, 0x11, 0xd1, 0xf5, 0x9d, 0x24, 0x0a, 0xbd, 0x24, 0xee, 0x00, 0x11, 0xe9, 0x11,
	0x42, 0x40, 0xaa, 0xe7, 0xda, 0xb2, 0xb0, 0x2e, 0xb4, 0xe7, 0x3b, 0xab, 0xa3, 0x54, 0x6d, 0x1e,
	0x62, 0xdf, 0x7b, 0xac, 0x8d, 0x73, 0x9a, 0x59, 0x87, 0x47, 0xd7, 0xce, 0xba, 0x80, 0x73, 0xd6,
	0xf5, 0xdf, 0xd9, 0xae, 0x71, 0x4e, 0x33, 0xeb, 0xf0, 0xe8, 0xda, 0xd2, 0x53, 0xb4, 0x58, 0x64,
	0x62, 0x86, 0x59, 0x12, 0xcb, 0x73, 0xeb, 0x42, 0xbb, 0xde, 0x59, 0x1b, 0xa5, 0xea, 0x6a, 0xb5,
	0x33, 0xcf, 0x6b, 0x66, 0x03, 0x02, 0x3b, 0xfc, 0x2d, 0x7d, 0x16, 0xd0, 0x0a, 0x44, 0x88, 0xdd,
	0xeb, 0x53, 0xcf, 0xc3, 0x8c, 0x44, 0xd8, 0x93, 0xe7, 0xd7, 0x85, 0xf6, 0xd5, 0x07, 0x6b, 0x7a,
	0xbe, 0x01, 0x3d, 0xdb, 0x40, 0xb1, 0x4d, 0x7d, 0x93, 0xba, 0x41, 0xe7, 0xe5, 0x71, 0xaa, 0xd6,
	0x46, 0xa9, 0x7a, 0xb3, 0x32, 0xa7, 0x02, 0xa2, 0xfd, 0x4e, 0xd5, 0xbb, 0x8e, 0xcb, 0xf6, 0x13,
	0x4b, 0xef, 0x53, 0xdf, 0x80, 0x6d, 0xe6, 0x3f, 0xee, 0xc7, 0xf6, 0xc0, 0x60, 0x87, 0x21, 0x89,
	0x39, 0x9e, 0xb9, 0x5c, 0x22, 0x6c, 0x96, 0x00, 0xd2, 0x3d, 0x24, 0x66, 0x3b, 0x22, 0x91, 0xbc,
	0xc0, 0xff, 0xb0, 0xe6, 0x28, 0x55, 0x1b, 0xe3, 0x45, 0x92, 0x48, 0x33, 0xa1, 0x40, 0x7a, 0x83,
	0xe6, 0x2c, 0xd7, 0x96, 0xc5, 0x69, 0xbc, 0x9f, 0x00, 0x6f, 0x54, 0xc2, 0xcc, 0x44, 0x33, 0x1b,
	0x22, 0xf9, 0xa8, 0x59, 0xdc, 0xb1, 0x94, 0x8c, 0xfc, 0x3f, 0x9f, 0xdc, 0xd2, 0x73, 0x51, 0xe9,
	0x85, 0xa8, 0xf4, 0xdd, 0xa2, 0xa2, 0x73, 0x1b, 0x46, 0xcb, 0x55, 0x29, 0x94, 0x10, 0xda, 0xd1,
	0x0f, 0x55, 0x30, 0x97, 0x20, 0x5e, 0xf6, 0x65, 0x67, 0x2e, 0x6a, 0xe1, 0xcc, 0x57, 0xce, 0x9e,
	0xb9, 0x9a, 0xd7, 0xcc, 0x06, 0x04, 0xe0, 0xcc, 0x2f, 0x90, 0x54, 0x08, 0xc1, 0xc7, 0x61, 0x08,
	0xe2, 0xac, 0x73, 0x99, 0xdd, 0x1a, 0xa5, 0xea, 0x5a, 0x55, 0x2c, 0xe3, 0x1a, 0xcd, 0x5c, 0x82,
	0xe0, 0x76, 0x1e, 0xeb, 0xda, 0x52, 0x1b, 0x89, 0x38, 0x0c, 0x33, 0x00, 0xc4, 0x01, 0x26, 0x8e,
	0x92, 0xc7, 0x35, 0x73, 0x01, 0x87, 0x61, 0xd7, 0xd6, 0xde, 0x8b, 0xe8, 0xda, 0x16, 0xb1, 0xd8,
	0x05, 0x35, 0xc7, 0x07, 0x01, 0x2d, 0xd2, 0x84, 0xed, 0x79, 0xf4, 0xa0, 0xc7, 0xe8, 0x80, 0x04,
	0xf1, 0x74, 0x5b, 0x3c, 0x87, 0x1b, 0xc3, 0x84, 0x6a, 0xfb, 0x4c, 0x4a, 0x6b, 0x40, 0xef, 0x2e,
	0x6f, 0xbd, 0xb4, 0xc2, 0xc5, 0xb6, 0xc2, 0x37, 0x11, 0x35, 0xb6, 0x12, 0xd6, 0xdf, 0xbf, 0xa0,
	0x5e, 0xf8, 0x24, 0xa0, 0x95, 0x8a, 0x98, 0x7b, 0xd8, 0xa7, 0x49, 0xc0, 0x66, 0xfe, 0x47, 0x71,
	0x1e, 0xc8, 0x4c, 0xb2, 0x93, 0x26, 0x7d, 0xf1, 0x8c, 0xf7, 0x4b, 0x1f, 0x05, 0xb4, 0xec, 0x06,
	0x7f, 0x93, 0x5b, 0x98, 0x46, 0x6e, 0x1b, 0xc8, 0xb5, 0x72, 0x72, 0xe7, 0x60, 0xcc, 0xc4, 0xad,
	0x99, 0x03, 0x4c, 0x52, 0x1b, 0xfb, 0x56, 0x9c, 0xe6, 0xdb, 0x4b, 0x2f, 0xfd, 0x93, 0x97, 0x3a,
	0xaf, 0x8e, 0x7f, 0x29, 0xb5, 0xaf, 0x43, 0xa5, 0x76, 0x3c, 0x54, 0x84, 0x93, 0xa1, 0x22, 0xfc,
	0x1c, 0x2a, 0xc2, 0xd1, 0xa9, 0x52, 0x3b, 0x39, 0x55, 0x6a, 0xdf, 0x4f, 0x95, 0xda, 0x6b, 0x63,
	0xe2, 0x60, 0x3e, 0x1d, 0xb8, 0x0c, 0x07, 0x84, 0x1d, 0xd0, 0x68, 0x60, 0xc0, 0x77, 0xe4, 0xbb,
	0xf2, 0x4b, 0x92, 0x5f, 0xcf, 0x12, 0xf9, 0x5e, 0x1f, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x40,
	0x46, 0x7d, 0xc5, 0x68, 0x0a, 0x00, 0x00,
}

func (m *SurplusBiddings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SurplusBiddings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SurplusBiddings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AppId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x50
	}
	if m.AuctionMappingId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AuctionMappingId))
		i--
		dAtA[i] = 0x48
	}
	if len(m.BiddingStatus) > 0 {
		i -= len(m.BiddingStatus)
		copy(dAtA[i:], m.BiddingStatus)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.BiddingStatus)))
		i--
		dAtA[i] = 0x42
	}
	n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.BiddingTimestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.BiddingTimestamp):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintBiddings(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Bid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBiddings(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.AuctionedCollateral.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBiddings(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.AuctionStatus) > 0 {
		i -= len(m.AuctionStatus)
		copy(dAtA[i:], m.AuctionStatus)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.AuctionStatus)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AuctionId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x10
	}
	if m.BiddingId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.BiddingId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DebtBiddings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DebtBiddings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DebtBiddings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AppId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x50
	}
	if m.AuctionMappingId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AuctionMappingId))
		i--
		dAtA[i] = 0x48
	}
	if len(m.BiddingStatus) > 0 {
		i -= len(m.BiddingStatus)
		copy(dAtA[i:], m.BiddingStatus)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.BiddingStatus)))
		i--
		dAtA[i] = 0x42
	}
	n4, err4 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.BiddingTimestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.BiddingTimestamp):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintBiddings(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x3a
	{
		size, err := m.Bid.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBiddings(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0x2a
	}
	{
		size, err := m.OutflowTokens.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBiddings(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.AuctionStatus) > 0 {
		i -= len(m.AuctionStatus)
		copy(dAtA[i:], m.AuctionStatus)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.AuctionStatus)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AuctionId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x10
	}
	if m.BiddingId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.BiddingId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DutchBiddings) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DutchBiddings) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DutchBiddings) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AppId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AppId))
		i--
		dAtA[i] = 0x50
	}
	if m.AuctionMappingId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AuctionMappingId))
		i--
		dAtA[i] = 0x48
	}
	if len(m.BiddingStatus) > 0 {
		i -= len(m.BiddingStatus)
		copy(dAtA[i:], m.BiddingStatus)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.BiddingStatus)))
		i--
		dAtA[i] = 0x42
	}
	n7, err7 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.BiddingTimestamp, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.BiddingTimestamp):])
	if err7 != nil {
		return 0, err7
	}
	i -= n7
	i = encodeVarintBiddings(dAtA, i, uint64(n7))
	i--
	dAtA[i] = 0x3a
	if len(m.Bidder) > 0 {
		i -= len(m.Bidder)
		copy(dAtA[i:], m.Bidder)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.Bidder)))
		i--
		dAtA[i] = 0x32
	}
	{
		size, err := m.InflowTokenAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBiddings(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.OutflowTokenAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintBiddings(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.AuctionStatus) > 0 {
		i -= len(m.AuctionStatus)
		copy(dAtA[i:], m.AuctionStatus)
		i = encodeVarintBiddings(dAtA, i, uint64(len(m.AuctionStatus)))
		i--
		dAtA[i] = 0x1a
	}
	if m.AuctionId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.AuctionId))
		i--
		dAtA[i] = 0x10
	}
	if m.BiddingId != 0 {
		i = encodeVarintBiddings(dAtA, i, uint64(m.BiddingId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintBiddings(dAtA []byte, offset int, v uint64) int {
	offset -= sovBiddings(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SurplusBiddings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BiddingId != 0 {
		n += 1 + sovBiddings(uint64(m.BiddingId))
	}
	if m.AuctionId != 0 {
		n += 1 + sovBiddings(uint64(m.AuctionId))
	}
	l = len(m.AuctionStatus)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	l = m.AuctionedCollateral.Size()
	n += 1 + l + sovBiddings(uint64(l))
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	l = m.Bid.Size()
	n += 1 + l + sovBiddings(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.BiddingTimestamp)
	n += 1 + l + sovBiddings(uint64(l))
	l = len(m.BiddingStatus)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	if m.AuctionMappingId != 0 {
		n += 1 + sovBiddings(uint64(m.AuctionMappingId))
	}
	if m.AppId != 0 {
		n += 1 + sovBiddings(uint64(m.AppId))
	}
	return n
}

func (m *DebtBiddings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BiddingId != 0 {
		n += 1 + sovBiddings(uint64(m.BiddingId))
	}
	if m.AuctionId != 0 {
		n += 1 + sovBiddings(uint64(m.AuctionId))
	}
	l = len(m.AuctionStatus)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	l = m.OutflowTokens.Size()
	n += 1 + l + sovBiddings(uint64(l))
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	l = m.Bid.Size()
	n += 1 + l + sovBiddings(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.BiddingTimestamp)
	n += 1 + l + sovBiddings(uint64(l))
	l = len(m.BiddingStatus)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	if m.AuctionMappingId != 0 {
		n += 1 + sovBiddings(uint64(m.AuctionMappingId))
	}
	if m.AppId != 0 {
		n += 1 + sovBiddings(uint64(m.AppId))
	}
	return n
}

func (m *DutchBiddings) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BiddingId != 0 {
		n += 1 + sovBiddings(uint64(m.BiddingId))
	}
	if m.AuctionId != 0 {
		n += 1 + sovBiddings(uint64(m.AuctionId))
	}
	l = len(m.AuctionStatus)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	l = m.OutflowTokenAmount.Size()
	n += 1 + l + sovBiddings(uint64(l))
	l = m.InflowTokenAmount.Size()
	n += 1 + l + sovBiddings(uint64(l))
	l = len(m.Bidder)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.BiddingTimestamp)
	n += 1 + l + sovBiddings(uint64(l))
	l = len(m.BiddingStatus)
	if l > 0 {
		n += 1 + l + sovBiddings(uint64(l))
	}
	if m.AuctionMappingId != 0 {
		n += 1 + sovBiddings(uint64(m.AuctionMappingId))
	}
	if m.AppId != 0 {
		n += 1 + sovBiddings(uint64(m.AppId))
	}
	return n
}

func sovBiddings(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozBiddings(x uint64) (n int) {
	return sovBiddings(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SurplusBiddings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBiddings
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SurplusBiddings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SurplusBiddings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingId", wireType)
			}
			m.BiddingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BiddingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionedCollateral", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.AuctionedCollateral.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.BiddingTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BiddingStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionMappingId", wireType)
			}
			m.AuctionMappingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionMappingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBiddings(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBiddings
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DebtBiddings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBiddings
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DebtBiddings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DebtBiddings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingId", wireType)
			}
			m.BiddingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BiddingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutflowTokens", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutflowTokens.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bid", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Bid.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.BiddingTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BiddingStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionMappingId", wireType)
			}
			m.AuctionMappingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionMappingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBiddings(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBiddings
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DutchBiddings) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowBiddings
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DutchBiddings: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DutchBiddings: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingId", wireType)
			}
			m.BiddingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BiddingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionId", wireType)
			}
			m.AuctionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuctionStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutflowTokenAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OutflowTokenAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InflowTokenAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.InflowTokenAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Bidder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Bidder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingTimestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.BiddingTimestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BiddingStatus", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthBiddings
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthBiddings
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BiddingStatus = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuctionMappingId", wireType)
			}
			m.AuctionMappingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AuctionMappingId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppId", wireType)
			}
			m.AppId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AppId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipBiddings(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthBiddings
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipBiddings(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowBiddings
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowBiddings
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthBiddings
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupBiddings
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthBiddings
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthBiddings        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowBiddings          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupBiddings = fmt.Errorf("proto: unexpected end of group")
)
